# --force-device-scale-factor=1.3
--ozone-platform-hint=auto
--enable-wayland-ime
# --gtk-version=4
--enable-features=TouchpadOverscrollHistoryNavigation
# --enable-features=VaapiVideoDecodeLinuxGL
# --use-gl=angle
