#
# $PARU_CONF
# /etc/paru.conf
# ~/.config/paru/paru.conf
#
# See the paru.conf(5) manpage for options

#
# GENERAL OPTIONS
#
[options]
PgpFetch
Devel
Provides
DevelSuffixes = -git -cvs -svn -bzr -darcs -always -hg -fossil
#AurOnly
#BottomUp
#RemoveMake
SudoLoop
#UseAsk
#SaveChanges
#CombinedUpgrade
#CleanAfter
#UpgradeMenu
NewsOnUpgrade

LocalRepo
Chroot
#Sign
#SignDb
#KeepRepoCache

[env]
all_proxy=http://127.0.0.1:7890
ALL_PROXY=http://127.0.0.1:7890
http_proxy=http://127.0.0.1:7890
https_proxy=http://127.0.0.1:7890
HTTP_PROXY=http://127.0.0.1:7890
HTTPS_PROXY=http://127.0.0.1:7890
CCACHE_DIR=/ccache
#RUSTC_WRAPPER=/usr/bin/sccache
#SCCACHE_DIR=/sccache

#
# Binary OPTIONS
#
[bin]
#FileManager = vifm
#MFlags = --skippgpcheck
#Sudo = doas
# https://wiki.archlinux.org/title/ccache#makechrootpkg
ChrootFlags = -d /home/mike/.cache/ccache:/ccache
# -d /home/mike/.cache/sccache:/sccache
