version = "1.1.14"

[class]
"(?i)waydroid.*" = "droid"
"(?i)Kitty" = "term"
"org.pwmt.zathura" = ""
Gvim = "🇻"
Alacritty = ""
Brave-browser = "🌍"
"org.gnome.Contacts" = ""
TelegramDesktop = "✈️"
libreoffice-writer = ""
emacs = "😈"
"[Ff]irefox" = ""
"org.gnome.Nautilus" = ""
QQ = ""
DEFAULT = "{class}"
Sxiv = "🖼️"
thunderbird = ""
"org.telegram.desktop" = ""
Zotero = "Z"
"com.github.xournalpp.xournalpp" = ""
GoldenDict = "📙"
Anki = "📇"

[class_active]

[initial_class]

[initial_class_active]

[workspaces_name]
0 = "zero"
10 = "ten"
9 = "nine"
8 = "eight"
4 = "four"
6 = "six"
7 = "seven"
3 = "three"
1 = "one"
5 = "five"
2 = "two"

[title_in_class.firefox]
".*Apple Music.*" = ""

[title_in_class."(?i)kitty"]
"(?i)neomutt" = "neomutt"

[title_in_class_active."(?i)firefox"]
"(?i)twitch" = "<span color='purple'>{icon}</span>"

[title_in_initial_class]

[title_in_initial_class_active]

[initial_title_in_class]

[initial_title_in_class_active]

[initial_title_in_initial_class]

[initial_title_in_initial_class_active]

[exclude]
"(?i)fcitx" = ".*"
"ueberzugpp*" = ""
"[Ss]team" = "^(Friends List.*)?$"
"" = "^$"
"(?i)TestApp" = ""
aProgram = "^$"

[format]
dedup = true
dedup_inactive_fullscreen = false
delim = " "
workspace = "<span color='#C3E88D'>{id}:</span>{delim}{clients}"
workspace_empty = "{id}"
client = "{icon}"
client_fullscreen = "[{icon}]"
client_active = "<span color='#C3E88D'>{icon}</span>"
client_dup = "{icon}{counter_sup}"
client_dup_active = "*{icon}*{delim}{icon}{counter_unfocused_sup}"
client_dup_fullscreen = "[{icon}]{delim}{icon}{counter_unfocused_sup}"
